import XCTest
@testable import TurtleDiverCore

final class ProfileSerializerTests: XCTestCase {

    /// Constant used to erase generated UUIDs before comparing round-tripped
    /// models (IDs are not part of the INI format and are regenerated).
    private let anyUUID = UUID(uuidString: "00000000-0000-0000-0000-000000000000")!

    private func erasingIDs(_ rules: [ProfileRule]) -> [ProfileRule] {
        rules.map { var c = $0; c.id = anyUUID; return c }
    }
    private func erasingIDs(_ groups: [ProxyGroup]) -> [ProxyGroup] {
        groups.map { var c = $0; c.id = anyUUID; return c }
    }
    private func erasingIDs(_ proxies: [ProxyDefinition]) -> [ProxyDefinition] {
        proxies.map { var c = $0; c.id = anyUUID; return c }
    }

    // MARK: - Round trip

    func testRoundTripFullProfile() throws {
        var profile = Profile(name: "RoundTrip")
        profile.general = GeneralSettings(
            httpListen: "127.0.0.1:6152",
            socks5Listen: "127.0.0.1:6153",
            testURL: "http://cp.cloudflare.com/generate_204",
            testTimeout: 4,
            testInterval: 300,
            systemProxy: true,
            skipProxy: ["127.0.0.1", "10.0.0.0/8", "*.local"],
            logLevel: "debug"
        )
        profile.proxies = [
            ProxyDefinition(name: "US", type: .http, host: "us.example.com", port: 8080, username: "alice", password: "s3,cret"),
            ProxyDefinition(name: "EU", type: .https, host: "eu.example.com", port: 443, skipCertVerify: true),
            ProxyDefinition(name: "HOME", type: .socks5, host: "192.168.1.1", port: 1080, tls: true)
        ]
        profile.groups = [
            ProxyGroup(name: "Auto", type: .urlTest, policies: ["US", "EU", "HOME"], testURL: "http://cp.cloudflare.com/generate_204", interval: 300),
            ProxyGroup(name: "Pick", type: .select, policies: ["Auto", "US", "DIRECT"]),
            ProxyGroup(name: "Backup", type: .fallback, policies: ["US", "EU"]),
            ProxyGroup(name: "Spread", type: .loadBalance, policies: ["US", "EU"])
        ]
        profile.rules = [
            ProfileRule(type: .domain, value: "exact.example.com", policy: "DIRECT"),
            ProfileRule(type: .domainSuffix, value: "apple.com", policy: "Pick"),
            ProfileRule(type: .domainKeyword, value: "github", policy: "Auto"),
            ProfileRule(type: .ipCIDR, value: "10.0.0.0/8", policy: "DIRECT", noResolve: true),
            ProfileRule(type: .ipCIDR6, value: "fd00::/8", policy: "HOME"),
            ProfileRule(type: .destPort, value: "443,8443,5000-6000", policy: "US"),
            ProfileRule(type: .processName, value: "ssh", policy: "DIRECT"),
            ProfileRule(type: .userAgent, value: "curl*", policy: "DIRECT"),
            ProfileRule(type: .urlRegex, value: "^https?://ads\\.", policy: "REJECT"),
            ProfileRule(type: .final, value: "", policy: "Pick")
        ]

        let text = ProfileSerializer.serialize(profile)
        let result = ProfileParser.parse(text, name: "RoundTrip")
        XCTAssertFalse(result.hasErrors, "Re-parse diagnostics: \(result.diagnostics)")

        let reparsed = result.profile
        // Phase 0 round-trip contract: model equality modulo UUID identity
        // (IDs are regenerated by the parser; names/policies are the keys).
        XCTAssertEqual(reparsed.name, profile.name)
        XCTAssertEqual(reparsed.general, profile.general)
        // https normalizes tls=true on re-parse; align the fixture the same way.
        var expectedProxies = profile.proxies
        expectedProxies[1].tls = true
        XCTAssertEqual(erasingIDs(reparsed.proxies), erasingIDs(expectedProxies))
        XCTAssertEqual(erasingIDs(reparsed.groups), erasingIDs(profile.groups))
        XCTAssertEqual(erasingIDs(reparsed.rules), erasingIDs(profile.rules))

        // And it must validate cleanly too.
        XCTAssertEqual(reparsed.validate(), [])
    }

    func testRoundTripMinimalProfile() {
        let profile = ProfileManager.makeDefaultProfile(name: "Main")
        let text = ProfileSerializer.serialize(profile)
        let result = ProfileParser.parse(text, name: "Main")
        XCTAssertFalse(result.hasErrors, "\(result.diagnostics)")
        XCTAssertEqual(result.profile.general, profile.general)
        XCTAssertEqual(erasingIDs(result.profile.proxies), erasingIDs(profile.proxies))
        XCTAssertEqual(erasingIDs(result.profile.groups), erasingIDs(profile.groups))
        XCTAssertEqual(erasingIDs(result.profile.rules), erasingIDs(profile.rules))
    }

    // MARK: - Formatting

    func testSerializerEmitsAllSections() {
        let text = ProfileSerializer.serialize(Profile(name: "X"))
        for section in ["[General]", "[Proxy]", "[Proxy Group]", "[Rule]"] {
            XCTAssertTrue(text.contains(section), "Missing section \(section)")
        }
        XCTAssertTrue(text.contains("FINAL,DIRECT"), "Empty profile should default to FINAL,DIRECT")
    }

    /// The generated header used to promise "Hand-edit freely; the app reloads
    /// on change", which is only half true: the app reloads the file, but the
    /// next in-app change rewrites it from the model, dropping comments and
    /// unknown options. The header has to say so.
    func testHeaderDoesNotPromiseThatHandEditsSurvive() {
        let text = ProfileSerializer.serialize(Profile(name: "X"))
        let header = text.split(separator: "\n").prefix { $0.hasPrefix("#") }.joined(separator: "\n")

        XCTAssertFalse(header.contains("Hand-edit freely"), header)
        XCTAssertTrue(header.lowercased().contains("rewritten"), header)
        XCTAssertTrue(header.lowercased().contains("not preserved"), header)
    }

    func testQuotingRoundTripForSpecialValues() throws {
        var profile = Profile(name: "Q")
        profile.rules = [
            ProfileRule(type: .domainSuffix, value: "we,ird.com", policy: "DIRECT")
        ]
        let text = ProfileSerializer.serialize(profile)
        XCTAssertTrue(text.contains("\"we,ird.com\""), "Comma value must be quoted: \(text)")
        let reparsed = ProfileParser.parse(text, name: "Q")
        XCTAssertEqual(reparsed.profile.rules.first?.value, "we,ird.com")
    }

    func testPasswordWithHashRoundTrips() throws {
        var profile = Profile(name: "P")
        profile.proxies = [
            ProxyDefinition(name: "A", type: .http, host: "h", port: 1, password: "ab#cd")
        ]
        let text = ProfileSerializer.serialize(profile)
        // password=ab#cd must be quoted so the # isn't treated as a comment.
        XCTAssertTrue(text.contains("password=\"ab#cd\""), "\(text)")
        let reparsed = ProfileParser.parse(text, name: "P")
        XCTAssertEqual(reparsed.profile.proxies.first?.password, "ab#cd")
    }

    func testHTTPSTypeDoesNotEmitRedundantTLS() {
        let proxy = ProxyDefinition(name: "E", type: .https, host: "h", port: 443, tls: true)
        let line = ProfileSerializer.proxyLine(proxy)
        XCTAssertFalse(line.contains("tls=true"), "https implies tls: \(line)")
    }

    func testNoResolveSerialized() {
        let rule = ProfileRule(type: .ipCIDR, value: "10.0.0.0/8", policy: "DIRECT", noResolve: true)
        XCTAssertEqual(ProfileSerializer.ruleLine(rule), "IP-CIDR,10.0.0.0/8,DIRECT,no-resolve")
    }
}
