import Foundation

/// Serializes a `Profile` back to Surge-compatible INI text.
///
/// Round-trip guarantee: for any `Profile` produced by the parser,
/// `ProfileParser.parse(ProfileSerializer.serialize(p)).profile == p`
/// (model-level fidelity; comments and unknown foreign options are not
/// preserved, matching the documented scope in docs/PROFILES.md).
public enum ProfileSerializer {

    /// Serializes the full profile.
    public static func serialize(_ profile: Profile) -> String {
        var out: [String] = []
        out.append("# TurtleDiver profile — Surge-compatible INI")
        out.append("#")
        out.append("# Generated by TurtleDiver from its own model, and rewritten whenever")
        out.append("# a setting changes in the app. A hand edit is picked up (the app watches")
        out.append("# the file), but the next in-app change regenerates the file from the")
        out.append("# model — so comments, blank lines and options this app does not know")
        out.append("# about are not preserved. Use the app's Rules/Routing screens for changes")
        out.append("# you want to keep.")
        out.append("")

        out.append("[General]")
        let g = profile.general
        out.append("http-listen = \(g.httpListen)")
        out.append("socks5-listen = \(g.socks5Listen)")
        out.append("test-url = \(g.testURL)")
        out.append("test-timeout = \(g.testTimeout)")
        out.append("test-interval = \(g.testInterval)")
        out.append("system-proxy = \(g.systemProxy ? "true" : "false")")
        out.append("skip-proxy = \(g.skipProxy.joined(separator: ", "))")
        out.append("loglevel = \(g.logLevel)")
        out.append("")

        out.append("[Proxy]")
        if profile.proxies.isEmpty {
            out.append("# No upstream proxies defined")
        }
        for proxy in profile.proxies {
            out.append(proxyLine(proxy))
        }
        out.append("")

        out.append("[Proxy Group]")
        if profile.groups.isEmpty {
            out.append("# No policy groups defined")
        }
        for group in profile.groups {
            out.append(groupLine(group))
        }
        out.append("")

        out.append("[Rule Set]")
        if profile.ruleSets.isEmpty {
            out.append("# No remote rule sets defined")
        }
        for set in profile.ruleSets {
            out.append(ruleSetLine(set))
        }
        out.append("")

        out.append("[Rule]")
        if profile.rules.isEmpty {
            out.append("FINAL,DIRECT")
        } else {
            for rule in profile.rules {
                out.append(ruleLine(rule))
            }
        }
        out.append("")

        return out.joined(separator: "\n")
    }

    // MARK: - Line builders

    static func proxyLine(_ proxy: ProxyDefinition) -> String {
        var parts: [String] = [proxy.type.rawValue, quoteIfNeeded(proxy.host), String(proxy.port)]
        if let username = proxy.username { parts.append("username=\(quoteIfNeeded(username))") }
        if let password = proxy.password { parts.append("password=\(quoteIfNeeded(password))") }
        if proxy.tls && proxy.type != .https { parts.append("tls=true") }
        if proxy.skipCertVerify { parts.append("skip-cert-verify=true") }
        return "\(proxy.name) = " + parts.joined(separator: ", ")
    }

    static func groupLine(_ group: ProxyGroup) -> String {
        var parts: [String] = [group.type.rawValue]
        parts.append(contentsOf: group.policies.map(quoteIfNeeded))
        if let url = group.testURL { parts.append("url=\(quoteIfNeeded(url))") }
        if let interval = group.interval { parts.append("interval=\(interval)") }
        return "\(group.name) = " + parts.joined(separator: ", ")
    }

    static func ruleSetLine(_ set: RemoteRuleSet) -> String {
        var line = "\(set.name) = \(set.url)"
        if let interval = set.interval { line += ", interval=\(interval)" }
        return line
    }

    static func ruleLine(_ rule: ProfileRule) -> String {
        if rule.type == .final {
            var parts = ["FINAL", rule.policy]
            if rule.noResolve { parts.append("no-resolve") }
            return parts.joined(separator: ",")
        }
        var parts = [rule.type.rawValue, quoteIfNeeded(rule.value), rule.policy]
        if rule.noResolve { parts.append("no-resolve") }
        return parts.joined(separator: ",")
    }

    /// Wraps a value in double quotes when it contains characters that would
    /// confuse the top-level comma splitter (commas, quotes, whitespace).
    /// Inner quotes are escaped by doubling them (`""`), matching INI style.
    static func quoteIfNeeded(_ value: String) -> String {
        let needsQuoting = value.isEmpty
            || value.contains(",")
            || value.contains("\"")
            || value.contains("#")
            || value.contains(";")
            || value != value.trimmingCharacters(in: .whitespaces)
        guard needsQuoting else { return value }
        let escaped = value.replacingOccurrences(of: "\"", with: "\"\"")
        return "\"\(escaped)\""
    }

    /// Inverse of `quoteIfNeeded` for values read back during tests.
    static func unquoteIfNeeded(_ value: String) -> String {
        guard value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 else { return value }
        let inner = String(value.dropFirst().dropLast())
        return inner.replacingOccurrences(of: "\"\"", with: "\"")
    }
}
